# run pre-commit install
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort --check-only
        types: [python]
        args: ["--line-length", "88", "--profile", "black", "--filter-files"]
        exclude: ^(docs/.*|tests/.*)$
  - repo: https://github.com/psf/black
    rev: 24.1.0  # IF VERSION CHANGES --> MODIFY "blacken-docs" MANUALLY AS WELL!!
    hooks:
      - id: black
        name: black
        args: ["--line-length", "88"]
        exclude: ^(docs/.*|tests/.*)$
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=23.3.0]
        exclude: ^(docs/.*|tests/.*)$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E203,E266,W503,B905,W605"
          - "--max-complexity=10"
        exclude: ^(docs/.*|tests/.*)$
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        exclude: ^(docs/.*|tests/.*)$
        args:
          - "--ignore=D100,D101,D104,D105,D107,D402,D203,D213"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^(docs/.*|tests/.*)$

